### PR TITLE
Added ability to Tie with standard html elements as well as form elements, and succes and failure callbacks, and docuementation

### PR DESCRIPTION
**Pull request by msaspence**
Added the ability to tie model instance attributes to non form html elements (includes test).

Added ability to define success and failure callback for a tie (includes tests).

Added some documentation for Tie, mostly taken from the GitHub Gist here:
https://gist.github.com/733106

Also slipped in some more tests for Validation didn't mean to but this is my first go with Git so please forgive, can't believe they will do any harm.

### CODE REVIEW

**Comment by jupiterjs** [comment]
Thanks.  What are success and failure for?

**Comment by msaspence** [comment]
Just a way to define callbacks for the syncing of values

Success is called when the value or attribue has been successfully set, and failure when it has not is the modal has returned a validation error

I'm using success to fire off a save and failure to render and display an error message

**Comment by jupiterjs** [comment]
wouldn't one want to listen to the model directly instead of using tie?

**Comment by justinbmeyer** [comment]
I think tie is fading b/c of templated bindings.  Closing this for now.  If you give me an answer for why you wouldn't want to listen to the model directly, I will reopen.  Thanks!

**Comment by msaspence** [comment]
call me lazy but simply because tie is much quicker to implement
you could extend your argument to why not listen to the dom (input elements) directly and eliminant tie altogether

**Comment by justinbmeyer** [comment]
I agree that tie is easier to setup cross binding, but not for listening to success and error.

**Pull request closed without merging**
