### PR TITLE
Prevent controller/view from duplicating suffix when suffix is present

### PR DESCRIPTION
**Pull request by jschilli**
alternate fix for https://github.com/jupiterjs/jquerymx/pull/29

current master code duplicates suffix if a view template has an explicit suffix

``` javascript
this.view('list'); // results in a fetch for 'list.ejs' 
this.view('list.mustache'); // results in 'list.mustache.mustache' s/b 'list.mustache'
```

I've added a test to ensure this covers this case, the existing test for controller/view covers the first case.

The case where a non string view request (a DOM element) is unchanged.

### CODE REVIEW

**Comment by moschel** [comment]
Didn't you forget to check in your init.micro.ejs template that you're testing?

**Comment by jschilli** [comment]
No, in the 2nd test, I reset the default view extension to '.ejs' and then explicitly load 'init.micro' which already exists

Trying to save bits :-)

**Comment by moschel** [comment]
Cool.   Thanks!

**Comment by jschilli** [comment]
For the avoidance of doubt, I explicitly set the jQuery.View.ext because it was set to '.micro' in the first test and seems to hang around.  Its on my list to understand the extent of tear down in qunit

**Comment by daffl** [comment]
Cool, definitely nicer than my patch.

**Pull request merged**
