### PR TITLE
form_params() output values problem

### PR DESCRIPTION
**Pull request by tqwhite**
form_params() was incorrectly returning scalar form values as arrays, here it only returns array for checkbox.

### CODE REVIEW

**Comment by ralphholzmann** [comment]
Hey, thanks for the pull request! At the same time you submitted this request, I've was writing some tests for these bugs, so I'll pull in your changes, run them against my tests and hopefully we'll be good to go. Thanks.

**Comment by tqwhite** [comment]
Terrific. I'm glad to hear it.

Have a good day.

tqii

TQ White II
Website  tqwhite.com
Phone  708-763-0100

**Comment by ralphholzmann** [comment]
@tqwhite The latest master should fix your issue. The expectation for this plugin is, if there's a single named checkbox in your form, it should return the scalar value for that checkbox. However, if there are multiple checkboxes on the form with the same name, it should return an array of scalar values, even if only one checkbox was checked. I've added tests for this to the latest master.

**Comment by tqwhite** [comment]
That's great. 

Thanks for your work on the framework. It's a great help to me.

best,
tqii

TQ White II
Website  tqwhite.com
Phone  708-763-0100

**Pull request merged**
