### PR TITLE
Serialized values should be sent with request

### PR DESCRIPTION
**Pull request by thecountofzero**
I think this will fix the issue with Model Lists not being serialized on updates and creates.

### CODE REVIEW

**Comment by moschel** [comment]
Hah, I just found this yesterday and was going to fix it too but you beat me to it.  Thanks!  Can you please include a test for this?

**Comment by thecountofzero** [comment]
Kinda new to this github and pull request thing. I "think" i just added a
test. Really wasn't sure how we provide a test for this.

I added one that checks for the "unwanted" values such as "_use_call",
"_data", etc that are part of a Model.List that we don't want sent with the
save.

I did notice that this test fails with the error message "Died on test #1:
this.Class is undefined" when makeRequest uses self.attrs() instead of
self.serialize()

So the test fails, but for a different reason than the actual qunit tests I
put in there.

**Comment by moschel** [comment]
So does the test pass with your change?

**Comment by thecountofzero** [comment]
Yes, but I "think" any test that saves a model that has associations would
fail without my change.

**Comment by moschel** [comment]
Oh ok.  Well thats good.  I was expecting the test to actually test providing a serialize object though, kinda like converters but the opposite:

serialize: 
  date: function(){
    // logic that converts from a date object to a string the server wants
  }

**Comment by thecountofzero** [comment]
Ah. Gotcha. I will poke around and add a more appropriate test later.

**Comment by brianmoschel** [comment]
Any chance you could add this today?  I'd like to get this pulled in since I might need it soon.

**Comment by thecountofzero** [comment]
I just added a test, but not sure it was what you were asking for. The test
does this. A model has an association to another model. That other model
provides it's own serialize method. The test makes
sure that serialize method is called on the associated model on save.

Not sure how to provide a serialize object. Is this type of stuff possible?

serialize:
 date: function(){
   // logic that converts from a date object to a string the server wants
 }

**Comment by brianmoschel** [comment]
Yeah I was looking for a test for serialize objects with types like dates.  I'll pull this in and add my own test for that.

Thanks.

**Comment by thecountofzero** [comment]
Yeah man. Sorry, still learning new stuff about JMVC every day.

What is the correct syntax for declaring a serialize function for types like
dates?

**Comment by moschel** [comment]
It should work the same way as converters, in reverse (if its working
correctly).

On Wed, Aug 3, 2011 at 1:59 PM, thecountofzero <
reply@reply.github.com>wrote:

> Yeah man. Sorry, still learning new stuff about JMVC every day.
> 
> What is the correct syntax for declaring a serialize function for types
> like
> dates?
> 
> On Wed, Aug 3, 2011 at 1:57 PM, brianmoschel <
> reply@reply.github.com>wrote:
> 
> > Yeah I was looking for a test for serialize objects with types like
> > dates.
> >  I'll pull this in and add my own test for that.
> > 
> > Thanks.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jupiterjs/jquerymx/pull/47#issuecomment-1720110
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jupiterjs/jquerymx/pull/47#issuecomment-1720130

## 

Brian Moschel

Jupiter Consulting
\Development\Training\Support
847-727-1609
brian.moschel@gmail.com

**Comment by moschel** [comment]
This is the type of test I mean:

https://github.com/jupiterjs/jquerymx/commit/59678c4cc213fd78a3bfc2ebee367e2f14085ec9 

Thanks for helping get this fixed.

**Comment by thecountofzero** [comment]
Very cool. Thanks for sharing.

Still have much to learn, I do..... [Insert curious Yoda-like hmmmmmmm here]

**Pull request merged**
