### PR TITLE
Small updates to wrap() and wrapMany() to honor model() and models() overrides, and docs

### PR DESCRIPTION
**Pull request by matthewryanscott**
See https://github.com/jupiterjs/jquerymx/pull/39 instead

### CODE REVIEW

**Comment by matthewryanscott** [comment]
Moving this pull request to a branch other than 'master' in my fork.

**Comment by jupiterjs** [comment]
Thanks, but

steal.dev.warn('wrap(attributes) is deprecated; use model(attributes) instead');

steal can not clean up parenthesis inside the string.  Can you change the warning?

**Comment by matthewryanscott** [comment]
Yes, I can do that, but before I do so, I am curious what you mean by not
cleaning up parentheses.  As it is, when I was making sure the patch did
what I wanted it to, I got this in my debugging console:

steal.js WARNING: wrapMany(instancesRawData) is deprecated; use
models(instancesRawData) instead

Is there some hidden behavior that this is potentially triggering that we
want to avoid?  Looking at the code for warn() in dev.js I didn't see
anything jump out at me telling me to avoid parens.

**Comment by jupiterjs** [comment]
when you compress, it won't be able to remove this.  This is a bug in steal that needs to be fixed by changing to a tokenizer from a regex.

**Comment by matthewryanscott** [comment]
See https://github.com/jupiterjs/jquerymx/pull/39 for the updated pull request containing the fix you mentioned (I couldn't change this to a topic branch after I created it, so I closed it and opened a new pull request)

**Pull request closed without merging**
