### PR TITLE
Added isAttrDirty function to backup.js

### PR DESCRIPTION
**Pull request by thecountofzero**
This will allow you to find out if an attribute of a model instance is dirty. If the attribute does not exist this will return false. I have also updated the unit tests.

### CODE REVIEW

**Comment by jupiterjs** [comment]
Thanks, but could we just make isDirty take an attr name?

.isDirty('age') ? 

In general, I like keeping as few functions for people to know as possible.

**Comment by thecountofzero** [comment]
I think that is a great idea. One question though. isDirty currently takes an optional parameter called checkAssociations. Since this new attribute parameter is also optional, what is the best way to handle a function that takes multiple optional parameters?

**Comment by jupiterjs** [comment]
typeof arg === 'string' vs 'boolean'

**Comment by thecountofzero** [comment]
Cool. I was in the middle of doing that when I saw your response. I swear!

Closing this request and will open a new one with updated code.

**Pull request closed without merging**
