### PR TITLE
Fix for automatically generated view paths of controllers in sub directories

### PR DESCRIPTION
**Pull request by lastzero**
I noticed that the automatically generated view path is not consistent for controller in sub directories like Myproject.Controllers.Foo.Bar. If you used this.view() in that controller, it would search in myproject/controllers/foo/bar/views/ instead of myproject/views/foo/bar/:

```
$.Controller.extend("Myproject.Controllers.Foo.Bar", {
   init: function() {
      // Did load myproject/controllers/foo/bar/views/init.ejs
      this.element.html(this.view());  
   }
});
```

Please review my changes - maybe it's possible to minimize the code even further or improve performance. Or the strange view path is a feature and not a bug?

### CODE REVIEW

**Comment by moschel** [comment]
For reference, you're talking about this forum post:

http://forum.javascriptmvc.com/topic/naming-convention-for-views-when-using-the-jquery-controller-view-plugin

**Comment by moschel** [comment]
The file organization enforced by controller/view is based on 2.0, not 3.0.  But we haven't really documented the 3.0 organization, this change shouldn't break any existing functionality, and it fixes a problem with apps that are written 2.0-style, so I have no problem with it.

I merged your changes locally in my repo, but they broke the existing controller/view tests, so I can't push.  I'll see if I can figure out why.

**Comment by moschel** [comment]
Easiest way to test this is making calculatePosition public and testing the path it returns.

**Comment by moschel** [comment]
I committed a fix and a test here:

https://github.com/jupiterjs/jquerymx/commit/99a524a48d36ad3c8bacdbc37a6320f6a392b408

Please let me know if this resolves the issue for you.  It shouldn't affect any current usage of controller/view.

**Comment by lastzero** [comment]
Cool, thanks! I'll test this ASAP.

**Comment by lastzero** [comment]
If you don't see any complaints within a week, we can assume it works.

**Pull request closed without merging**
