### PR TITLE
Pluginname fix

### PR DESCRIPTION
**Pull request by daffl**
Fix for problems with setting a controllers pluginname as reported in
http://forum.javascriptmvc.com/#topic/32525000000253001
and http://forum.javascriptmvc.com/#topic/32525000000488001

I added the according tests to controller_test.js.

### CODE REVIEW

**Comment by daffl** [comment]
Hm, didn't want to include my controller view suffix change. But I can add some tests for that as well.

**Comment by wclr** [comment]
one more problem with pluginName 
http://forum.javascriptmvc.com/#Topic/32525000000591221
(solution is there)

**Comment by daffl** [comment]
I think I fixed this in my development branch but didn't turn it into a new pull request yet. Can you have a look if it is being tested here: https://github.com/daffl/jquerymx/blob/master/controller/controller_test.js

**Comment by daffl** [comment]
Please let me know when/if the requests might get merged for the 3.2 release so that I can test if everything still works with the latest jquerymx.

Thanks

**Comment by daffl** [comment]
Closing, will create and merge new pull requests.

**Pull request closed without merging**
