### PR TITLE
jquerymx controller should perform deep extend when merging incoming options with defaults

### PR DESCRIPTION
**Pull request by caseyheckman**

### CODE REVIEW

**Comment by jupiterjs** [comment]
I've thought about this. But, if someone does:

var foo = {};
foo.bar = foo;

$().mycontroller(foo);

Controller will go crazy.

Also, it copies property by property.  I am often passing in Models and complex data structures.  How would this work?

**Comment by caseyheckman** [comment]
Although undocumented, jQuery's extend() addresses both of these concerns.  It has checking for infinite recursion, and does not copy the property in cases where that would occur.  And, it only copies "plain" objects (using jQuery.isPlainObject() to make the determination).  Also note: it will not merge arrays.

**Comment by jupiterjs** [comment]
I tried this

var foo = {};
foo.bar = foo;
$.extend(true, {}, foo);

 and I got an infinite recursion error.  Are you sure?  Is this in 1.5 and not in 1.4?

**Comment by caseyheckman** [comment]
Ah, yes, you are correct. I misunderstood your example.  Your concern is valid, although in general one should probably avoid creating objects that are self-referential.  Looks like I'll just have to handle this a different way.  Thanks!

**Comment by jupiterjs** [comment]
I'm not sure my concern is 'extremely' valid.  No one might be doing this.  Self referential objects are bad.  But cycles can be common.
var foo = {};
var bar == {foo: foo}
foo.bar = bar;

But it's something to think about.  We could make the default this behavior and have a flag set on controllers that turns this off, or vice versa.

**Comment by jupiterjs** [comment]
We could write an extend plugin that overwrites $.extend with something that marks all objects with a temporary guid.  If a cycle is detected, it stops copying.

**Pull request closed without merging**
