### PR TITLE
Fixing controller/view suffix problem

### PR DESCRIPTION
**Pull request by daffl**
This is a small fix for a bug that occurs when using more than one view engine with the controller/view plugin:

```
this.view('test'); // --> Uses /controller/test.ejs when EJS is set as the default suffix
this.view('test.tmpl'); // --> Uses /controller/test.tmpl.tmpl but should use /controller/test.tmpl
```

### CODE REVIEW

**Comment by jupiterjs** [comment]
this looks like it is removing the suffix and adding the default.  Should it check if there is a suffix and only add one if one isn't there?

**Comment by daffl** [comment]
I think it is adding 

```
(typeof view == "string" && view.match(/\.[\w\d]+$/)) || jQuery.View.ext;
```

Which will add the default if no suffix is given in the view but it will add the matched suffix to the view name again if there is one here:

```
view = "//" + new steal.File('views/' + (view.indexOf('/') !== -1 ? view : (hasControllers ? controller_name + '/' : "") + view)).joinFrom(path) + suffix;
```

**Comment by jschilli** [comment]
Looks like this fix disappeared with the new async merge (which forked on June 7th)

Ouch.

**Comment by daffl** [comment]
I think there was some pull request confusion. It got never merged since I opened another one. It is still in my fork including the plugin name fix and some other smaller things that will hopefully make it into 3.2.

**Comment by jupiterjs** [comment]
you are a contributor now ... if it's a good fix, add it in!

**Pull request closed without merging**
