### PR TITLE
Pass XHR object to callback

### PR DESCRIPTION
**Pull request by dimaf**
Hi,
I had to do this change because in some model callbacks I needed to access HTTP headers, unfortunatelly before this information was not available.
Can imagine this feature could be useful for others.

Regards,
Dmytro

### CODE REVIEW

**Comment by justinbmeyer** [comment]
What case was this necessary?  I hesitate to add this b/c people use deferreds (I'm guessing this will change the resolved args).

**Comment by dimaf** [comment]
Our REST services are implemented that way so that when I create and save new model object (do POST on a resource) as a response I get 201 Created and the URL of  new resource in the Location HTTP header. 
I'm using deferred too, for this so it' works like this now.

var model=new MyModel(data);
model.save().done(function(m, data, status, jqXHR){
   var url = jqXHR.getResponseHeader("Location");
   ......
  }).fail(this.callback("onError"));

I need to have such a behavior to be conform wit the HTTP standard for creating resources
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by justinbmeyer** [comment]
I understand you need to get the location to often get the id of an object.  However, what are you doing with that url at that point?

Couldn't you add the url as data in create?

``` javascript
create : function(attrs, success, error){
  return $.post('/things', attrs, function(data, status, jqXHR) {
    success($.extend( data , {url: jqXHR.getResponseHeader("Location") } ) )
  },'json')
}
```

This would allow:

``` javascript
var model=new MyModel(data);
model.save().done(function(m){
  var url = m.url
}).fail(this.callback("onError"));
```

**Comment by dimaf** [comment]
Ok, can I overwrite the Model to provide such a create function centrally and available to all models and preferably still be using all the functionality the current create method from the model provides?
I still would like to use that simple model definition like this, and not to have to put any code in each model:

``` javascript
$.Model("Customer", { /* @Static */
    create : "POST /customer",
    findOne : "GET /customer/{id}",
    findAll : "GET /customer",
    update : "PUT /customer/{id}",
    destroy : "DELETE /customer/{id}"
}, { /* @Prototype */
});
```

**Comment by justinbmeyer** [comment]
Why do other models need the url / location header?  

IMO, the location as url isn't something that everyone needs, so it doesn't seem right to make it part of the simple model definition for their custom changes.  

I've thought about making the simple model definition's take objects, so you could do:

``` javascript
create : { type: "post", url : "/customer", dataType : 'json seturl'}
```

And make a seturl prefilter that would copy the location to the json data.

Would that work?

**Comment by justinbmeyer** [comment]
It could even work like:

```
create: "post /customer json seturl"
```

**Comment by dimaf** [comment]
All our  REST services will have such behavior, that is why all corresponding models will have to support it, and it's going to be a lot(100+). It depends on case to case how that URL is used, sometimes it'll be just ignored, sometimes I'll do get immediately  after, sometimes the url will be stored for later use or just parsed to get the ID part of it.

I think the fact that I may or may not need to use Location URL  should not influence in any way how the model is defined. So the current simple definition looks perfect. That's why i just thought to pass the whole XHR object as a last parameter and the caller can then decide if it wants to do something with it or just ignore. Also the existing code should not be influenced by the change.

Also i can imagine other HTTP response headers, not only Location, may be required at some stage too so just having the ability to access XHR object  in response callback gives  the whole flexibility.

**Comment by justinbmeyer** [comment]
Model should really encapsulate the data from the server.  The caller shouldn't deal with an Ajax request, but instead the model layer.  This makes it much less likely to change code if, for example, the url was moved from the location to a 'location' property on the data returned by the server.  The $.Model often provides a valuable buffer from service changes.

Would my suggestion work for you?

**Comment by prototype** [comment]
At times like these, it sucks to have "prototype" as a nickname on github
;-)

**Comment by dimaf** [comment]
Ok, agree, having caller access ajax request is not really clean. Have now changed my code to use ajaxPrefilter  the way  you mentioned above and it works with default simple model definition, I've just overwritten all POST requests, since in our case they all will get Location header back. 

In case of POST where no real response is coming it's ok now. But in case i may need to access HTTP headers during get or after update, and will use the same approach it will not be really nice too. Because the model will then contain attributes that i can not send back to the server, and will have to remove before update.

About making the simple model definition's take objects, so you could do:

create : { type: "post", url : "/customer", dataType : 'json seturl'}

we did this in our local version too but primary to be able to switch on/off fixtures selectively on individual models like this
create : { url : "/customer",fixture:"-restCreate"}
so by default all the fixtures are switched off on simple models, and only where explicitly specified they are switched on.
I can push that code to github too if this may be interesting, but this was also really small change.

**Comment by justinbmeyer** [comment]
yes, that would be a good patch.  

I am not sure what you mean about POST.

I'm going to change model and models to get called with the headers.  But I am going to close this issue.  Thanks for working through it with me.

**Pull request closed without merging**
